### PR TITLE
modules: fix FATAL_ERROR on compiler check

### PR DESCRIPTION
**Pull request by tomershafir**
Fix a CMake fatal error on `cmake/CxxModulesRules.cmake` compiler check.

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
thanks!

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help merge this change?

**Comment by tomershafir** [comment]
@xemul Can you share your reasons to not merge pull requests?

**Comment by mykaul** [comment]
> @xemul I wonder why didnt you merge the PR

@tomershafir - it's merged. See https://github.com/scylladb/seastar/commit/19dc73402514512faa8c7d344051f8f9dbe6d459

**Comment by xemul** [comment]
> @xemul I wonder why didnt you merge the PR

Because I'm not a bot, but a human, and merge PRs irregularly
2 hours delay between PR submission and merging is pretty nice timing I would say

**Comment by tomershafir** [comment]
sorry for confusion, I meant why didn't you use Github's interface to merge the PR, but rather git merge and closed the PR

**Comment by avikivity** [comment]
> > @xemul I wonder why didnt you merge the PR
> 
> Because I'm not a bot, but a human, and merge PRs irregularly 2 hours delay between PR submission and merging is pretty nice timing I would say

Don't believe him, he's a bot and uses irregular timing to mask it

**Comment by xemul** [comment]
> Sorry for the confusion, I meant why didn't you use Github's interface to merge the PR, instead of using plain git and closing the PR.

Ah 😳 Well, because I'm not a human, but a bot and use scripts around plain git instead of clicking on Github's interface buttons 🤖

**Pull request closed without merging**
