### PR TITLE
Limit memory address space per core to 64GB when hwloc is not available

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Currently, when hwloc is not available, we still observe a significant amount
of memory leakage when "total_avail_memory / cpu_num" is larger than 64GB. The
reason is quite similar to which led to commit https://github.com/scylladb/seastar/commit/cfec74de07994cdc500040f114243e0024181d00,
which is: when "total_avail_memory / cpu_num" is larger than 64GB, the last cpu
can allocate a piece of memory space outside its 64GB range and no other cpu
can free it.

This should be a complement for commit cfec74de07994cdc500040f114243e0024181d00

Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
@avikivity Hi, could you take a look at this pr, please? Thanks:-)

**Comment by xxhdx1985126** [comment]
@avikivity Hi, could you take a look at this pr, please? Thanks:-)

**Comment by avikivity** [comment]
Please adjust the patch changelog to explain why you're doing this.

**Comment by xxhdx1985126** [comment]
> Please adjust the patch changelog to explain why you're doing this.

By patch changelong, do you mean the commit message?:-)

**Comment by avikivity** [comment]
> > Please adjust the patch changelog to explain why you're doing this.
> 
> By patch changelong, do you mean the commit message?:-)

Yes

**Comment by xxhdx1985126** [comment]
> > > Please adjust the patch changelog to explain why you're doing this.
> > 
> > 
> > By patch changelong, do you mean the commit message?:-)
> 
> Yes

Done, please take a look again.

**Pull request merged**
