### PR TITLE
core: Reduce the default blocked-reactor-notify-ms to 25ms

### PR DESCRIPTION
**Pull request by asias**
A 200ms stall is way too much for most latency sensitive applications.
It makes more sense to use a smaller default number so the user will
know the stall and report.

### CODE REVIEW

**Comment by asias** [comment]
@avikivity @slivne FYI

**Comment by dorlaor** [comment]
I'm concerned that once we'll get to an area of blockage, we'll get tons of
log entries.
Would it be possible to silent it after 'enough' entries were printed? The
log automatically
does this but we may need even more quiet

**Comment by asias** [comment]
There is a limit already:
```
 blocked_reactor_reports_per_minute(*this, "blocked-reactor-reports-per-minute", 5, "Maximum number of backtraces reported by stall detector per minute")
```

**Comment by dorlaor** [comment]
Nice

**Review by tgrabiec — APPROVED** [review]

**Comment by avikivity** [comment]
We should make this configurable like task quota https://github.com/scylladb/seastar/blob/23385b0bac0f6ec055b009380f4ec1092a2bbc3c/include/seastar/core/app-template.hh#L57 so different applications can have their own stall thresholds. But 25ms is high enough so we can start with this.

**Pull request closed without merging**
