### PR TITLE
core: lw_shared_ptr: allow defining `lw_shared_ptr<T>` class member without knowing the definition of `T`

### PR DESCRIPTION
**Pull request by kbr-**
Before this change you couldn't do the following:

- Header file:
```
struct my_type;
struct my_struct {
    lw_shared_ptr<my_type>;
    ~my_struct();
}
```

- Implementation file:
```
struct my_type {
};

my_struct::~my_struct() = default;
```

This was because the definition of `lw_shared_ptr<T>` had an `accessors`
type, the definition of which required knowing `T` because it used
`is_base_of<..., T>`.

With this commit the above becomes possible. Consider, for example,
`trace_state_ptr` from Scylla, which is an `lw_shared_ptr<trace_state>`
underneath - and that's a pretty big class. Now defining classes with
`trace_state_ptr` fields or functions which take `trace_state_ptr`
parameter by value won't need the definition of `trace_state`.

To achieve that, `accessors` became a template. We only instantiate it
in the definitions of `lw_shared_ptr` member functions.

### CODE REVIEW

**Comment by avikivity** [comment]
Aha, so you force the compiler to treat it lazily so it doesn't notice it misses definitions.

Nice trick. Please link your account with circleci and make it check the branch. It seems like something compilers would complain about.

**Comment by kbr-** [comment]
> Please link your account with circleci and make it check the branch.

Is there a README somewhere?
cc @benipeled

**Comment by kbr-** [comment]
It seems this weird app doesn't let me build on any branch other than `master`

**Comment by avikivity** [comment]
Builds work for me on any branch, example https://app.circleci.com/pipelines/github/avikivity/seastar/205/workflows/8f85104c-1c9a-4c39-8632-c18bfdf6654c

**Comment by kbr-** [comment]
How do I start a build on a specific branch?

**Comment by michoecho** [comment]
> Now passing around trace_state_ptr won't need the definition of trace_state

What do you mean by "passing around" here? Without the definition of `trace_state` you still won't be able to pass `trace_state_ptr` by value, because you need the destructor (which needs the concrete type) for that, right? And passing it by reference is possible already.

**Comment by kbr-** [comment]
This is my list of branches:
image

**Comment by kbr-** [comment]
> What do you mean by "passing around" here? Without the definition of trace_state you still won't be able to pass trace_state_ptr by value, because you need the destructor (which needs the concrete type) for that, right? And passing it by reference is possible already.

Yes you're right. I'll just be able to define classes with `trace_state_ptr` fields without including the whole trace_state header.

**Comment by kbr-** [comment]
And function declarations which take `trace_state_ptr` by value.

**Comment by kbr-** [comment]
Ugh, I had to push the branch again after registering for circleci.

**Comment by nyh** [comment]
I need to look at your code, but I'm happy that you did it: Seven (!) years ago I sent a patch to the Seastar mailing list titled "[PATCH] Reimplement lw_shared_ptr" (Jul 12, 2015) with exactly the same stated goal: making it possible to use lw_shared_ptr<T> for a incomplete types T.

The trick that I used to avoid the need for that checking of T was:
"... the main observation is that lw_shared_ptr's assumption (of no polymorphism) allows implementing shared_from_this() without any overhead, because of the known size of the object and our allowing only make_shared() allows us to always figure out where the counter sits relative to the object. So we can implement *only* a variant which supports enable_shared_from_this. The trick is how to do this even without requiring the enable_shared_from_this base for the object."

I don't remember what was wrong with my patch 7 years ago. I think it was too big or something. Let's see how this one works.

**Comment by kbr-** [comment]
Anyway, do you guys see the circleci results? All builds passed.

**Review by psarna — APPROVED** [review]

**Comment by kbr-** [comment]
@avikivity could you merge please?

**Review by nyh — APPROVED** [review]

**Pull request closed without merging**
