### PR TITLE
Make io uring default

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
this change contains

- [ ] #1377
- [ ] #1389

once they get merged. i will remove them from this PR and mark it ready for review.

**Comment by dorlaor** [comment]
Great job! It will be great to test Scylla with io_uring and compare 1-2
cases
to check the performance gain

**Comment by avikivity** [comment]
Strangely, uring isn't detected on my machine (F37).

**Comment by avikivity** [comment]
Ah, we have         `'-DSeastar_IO_URING=OFF', # Fedora 34's liburing is too old`.

**Pull request merged**
