### PR TITLE
log: disambiguate formatter<log_level> from operator<<

### PR DESCRIPTION
**Pull request by bhalevy**
When using the colored logger (post dde522b1e) with scylla we
stumbled upon an anomaly where, when built in debug build mode,
`fmt::format_to(it, "{} ", level)` in do_log()
ends up invoking `operator<<(std::ostream& out, log_level level)`
which uses `log_level_names` that are in lower case.

It is still unclear why this happens, and
it doesn't reproduce with seastar unit tests
even in debug mode.

This change fixes the issue for scylla
by defining `wrapped_log_level` and respectively
`fmt::formatter<wrapped_log_level>`, and using
it explicitly in `do_log` by calling fmt::format_to
with a wrapped_log_level object.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
Cc @tchaikov

**Comment by tchaikov** [comment]
@bhalevy what's the fmt version and c++ compiler you are using? probably i could try to reproduce it using my own Seastar application? i am trying to visit https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1969/ but it tries to access my GitHub account.

**Comment by bhalevy** [comment]
> @bhalevy what's the fmt version and c++ compiler you are using? probably i could try to reproduce it using my own Seastar application? i am trying to visit https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1969/ but it tries to access my GitHub account.

We use clang++ 12.0.1 -std c++20 fmt version 7.1.3

**Comment by bhalevy** [comment]
But in any case, I don't like the ambiguity of operator<< vs. fmt::formatter for log_level.  It looks like the former method is required for printing and parsing log_level for command line args, so we can't simply remove it, so wrapping the log level for do_log seems like a good idea regardless.

**Comment by tchaikov** [comment]
neither do i. at least, we cannot avoid the ambiguity in the older version of fmt in a straightforward way.

the operator<< is used by `boost::program_options` for  print out the customized option types. as an alternative, we could specialize `boost::lexical_cast<>` for the enum type, like:
```diff
diff --git a/include/seastar/util/log.hh b/include/seastar/util/log.hh
index 28b66c17..c64ae3be 100644
--- a/include/seastar/util/log.hh
+++ b/include/seastar/util/log.hh
@@ -542,4 +542,8 @@ template <> struct fmt::formatter<std::exception> : fmt::ostream_formatter {};
 template <> struct fmt::formatter<std::system_error> : fmt::ostream_formatter {};
 #endif

+template<>
+std::string
+boost::lexical_cast<std::string, seastar::log_level>(const seastar::log_level& level);
+
 /// @}
diff --git a/src/util/log.cc b/src/util/log.cc
index 2cfac890..2392442b 100644
--- a/src/util/log.cc
+++ b/src/util/log.cc
@@ -251,10 +251,6 @@ const std::map<log_level, sstring> log_level_names = {
         { log_level::error, "error" },
 };

-std::ostream& operator<<(std::ostream& out, log_level level) {
-    return out << log_level_names.at(level);
-}
-
 std::istream& operator>>(std::istream& in, log_level& level) {
     sstring s;
     in >> s;
@@ -670,3 +666,9 @@ std::ostream& operator<<(std::ostream& out, const std::system_error& e) {
 }

 }
+
+template<>
+std::string
+boost::lexical_cast<std::string, seastar::log_level>(const seastar::log_level& level) {
+    return seastar::log_level_names.at(level);
+}
```

what do you think?

**Comment by bhalevy** [comment]
Unfortunately it breaks the api.
The change you proposed is incomplete, since you need to also delete the declaration:
```diff
diff --git a/include/seastar/util/log.hh b/include/seastar/util/log.hh
index 28b66c17..98c743ad 100644
--- a/include/seastar/util/log.hh
+++ b/include/seastar/util/log.hh
@@ -53,7 +53,6 @@ enum class log_level {
     trace,
 };
 
-std::ostream& operator<<(std::ostream& out, log_level level);
 std::istream& operator>>(std::istream& in, log_level& level);
 }
 
```

and with that, scylla doesn't compile.

For example:
```
./utils/config_file.hh:200:45: note: in instantiation of function template specialization 'seastar::format<const std::basic_string_view<char> &, const seastar::log_level &, std::vector<seastar::log_level> &>' requested here
                throw std::invalid_argument(format("Invalid value for {}: got {} which is not inside the set of allowed values {}", name(), t, _allowed_values));
                                            ^
```

**Pull request closed without merging**
