### PR TITLE
net/tcp: generate a random src_port hashed to current shard if smp::count > 1

### PR DESCRIPTION
**Pull request by sqddk**
I have fixed an issue in the TCP protocol stack related to the "connect" phase. Now, it will be modified to determine whether to randomly generate a port that can be hashed to the current core based on smp::count. This resolves the TCP connect failure issue occurring in my environment.

### CODE REVIEW

**Comment by avikivity** [comment]
The fix looks good, but please move the explanation into the patch changelog, so it will be visible in the git tree.

**Comment by sqddk** [comment]
> The fix looks good, but please move the explanation into the patch changelog, so it will be visible in the git tree.

no problem

**Comment by tchaikov** [comment]
also, please use a more descriptive title for the commit. i'd suggest use something like:

> net/tcp: generate a random src_port hashed to current shard if smp::count > 1

**Comment by sqddk** [comment]
> also, please use a more descriptive title for the commit. i'd suggest use something like:
> 
> > net/tcp: generate a random src_port hashed to current shard if smp::count > 1

Received! Benefited a lot.

**Comment by tchaikov** [comment]
you might need to revise the commit locally and force push to update it. the cover letter is not used in a single-commit merge.

**Comment by tchaikov** [comment]
> > also, please use a more descriptive title for the commit. i'd suggest use something like:
> > > net/tcp: generate a random src_port hashed to current shard if smp::count > 1
> 
> Received! Benefited a lot.

could you reconsider this suggestion?

and i'd suggest only use ASCII in the commit message. see also https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by tchaikov** [comment]
please replace "fix:" with "net/tcp:".

**Review by tchaikov — APPROVED** [review]
lgtm

**Pull request merged**
