### PR TITLE
Unfriend reactor from message queues

### PR DESCRIPTION
**Pull request by xemul**
The alien and smp ones need _sleeping and _stopped. Both can be patched to be part of the public API.

### CODE REVIEW

**Comment by xemul** [comment]
CI -- #2296

**Comment by avikivity** [comment]
> The alien and smp ones need _sleeping and _stopped. Both can be patched to be part of the public API.

Why should they be part of the public API? We don't want people to rely on them without a good reason.

**Comment by xemul** [comment]
The `_sleeping` doesn't become such, I just move it to existing `.wakeup()` one. I would be better to hide the latter in internal API indeed, but that's separate task. 

The `_stopped` ... yes, it appears to be a new method, but it's `const` and lightweight. So maybe it's OK until we hide it together with the `wakeup()`?

**Comment by xemul** [comment]
upd:
- marked the new `reactor::stopped()` with `/// @private` not to appear in docs
- rebased to pick up CI fix

**Comment by xemul** [comment]
> The `_sleeping` doesn't become such, I just move it to existing `.wakeup()` one. I would be better to hide the latter in internal API indeed, but that's separate task.
> 
> The `_stopped` ... yes, it appears to be a new method, but it's `const` and lightweight. So maybe it's OK until we hide it together with the `wakeup()`?

@avikivity , does this justify the change from you perspective?

**Comment by xemul** [comment]
@avikivity , reminder ping

**Comment by avikivity** [comment]
> upd:
> 
> * marked the new `reactor::stopped()` with `/// @private` not to appear in docs
> * rebased to pick up CI fix

I don't understand, you want stopped() to be @private, but not private:?

Reducing friendships is good, but it should cause us to break data hiding. If we want two classes to talk via a private channel, they can be friends.

**Comment by xemul** [comment]
> I don't understand, you want stopped() to be @Private, but not private:?

Yes. We need some way to tell that a specific method is public: but not intended to be used by any code outside of seastar itself. The @private marking looks like good enough approach.

> Reducing friendships is good, but it should cause us to break data hiding. If we want two classes to talk via a private  channel, they can be friends.

I agree, but friendship is pretty heavy hammer for reactor which is overloaded with functionality.

**Comment by avikivity** [comment]
I'm not totally happy about it, but we're splitting hairs, so okay.

In the past I sued friend free functions in the internal namespace.

**Pull request merged**
