### PR TITLE
Fix `fmt` lib version check

### PR DESCRIPTION
**Pull request by jbajic**
Fix `fmt` lib version check.

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
hi Jure, thank you for addressing this issue! could you please revise the commit message, so its title has prefix of `test/unit`, like "test/unit: fix fmt version check"?

so that we can tell that the severity of this issue just by reading the commit message?

**Review by tisonkun — APPROVED** [review]
Thank you! I just encounter the same issue and this patch helps.

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tisonkun** [comment]
cc @xemul

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help merge this change?

**Pull request closed without merging**
