### PR TITLE
stall-analyser: add output support for flamegraph

### PR DESCRIPTION
**Pull request by tchaikov**
a typical session is like:

```console
$ ./stall-analyser.py --format trace -e scylla/libexec/scylla \
  reactor_stalled_231d31df_2022_2_twcs_3h.log  > out.folded
$ flamegraph.pl out.folded > /tmp/folded.svg
$ xdg-open /tmp/folded.svg
```

### CODE REVIEW

**Comment by bhalevy** [comment]
Can you please upload an example of the result?

**Comment by tchaikov** [comment]
the log file and executable come from https://github.com/scylladb/scylladb/issues/11971
```console
$ ./stall-analyser.py --format trace -e scylla/libexec/scylla \
  reactor_stalled_231d31df_2022_2_twcs_3h.log | \
  flamegraph.pl --title 'Reactor Stalls' --countname "ms" > /tmp/folded.svg
$ xdg-open /tmp/folded.svg
```
[folded.log](https://github.com/scylladb/seastar/files/14845814/folded.log)
folded

**Comment by tchaikov** [comment]
@bhalevy hi Benny, if the general direction is sane. we could render an SVG on the fly without using the flamegraph, this way, we could customize the blocks further. but before that i will try to work on our in-house web service to hook up with this tool.

**Comment by bhalevy** [comment]
It looks nice visually, but I don't see how it helps understanding the stack traces any better.
Seems distracting to me.

**Comment by tchaikov** [comment]
@bhalevy hi Benny, thank you for your review. i think it does not provide more information, even worse, it provide less information than the text output. but the reason i added this output is not just for offering an eye candy. 

with a graph we can identify the the hotspot with a quick glance. then we can continue looking at the text output and the logging messages. it serves the same purpose of https://www.brendangregg.com/flamegraphs.html 

i am extracting the refactor part out into #2178. would be great to make stall-analyser an importable module in future.

**Pull request merged**
