### PR TITLE
core: enable seastar to run multiple times in a single process

### PR DESCRIPTION
**Pull request by tchaikov**
this series enables us to run multiple `seastar::app_template` instances sequentially in a single process. this is a false requirement in production, as we don't launch seastar app multiple times in a single process. but this is handy if we want to test, for instance, app_template in a single test process, where we need to start multiple app_template instances one after another.

### CODE REVIEW

**Comment by tchaikov** [comment]
i tested this change with the debug build of scylla:
```console
$ JAVA_HOME=/usr/lib/jvm/jre-11 pytest  -c $PWD/pytest.ini --cassandra-dir $HOME/dev/scylladb/build/Debug scylla_sstable_test.py
...
=========================================================================================== 3 passed, 8 warnings in 53.08s ===========================================================================================
```

**Comment by avikivity** [comment]
Please add a test that shows two app_templates, perhaps communicating with each other via seastar::alien.

**Comment by tchaikov** [comment]
v2:

- added a test run two instances of `app_template` in sequentially in a single process.

@avikivity the goal of this changeset is not to run multiple `app_template` instances in parallel, but to run them sequentially.

**Comment by avikivity** [comment]
> v2:
> 
> * added a test run two instances of `app_template` in sequentially in a single process.
> 
> @avikivity the goal of this changeset is not to run multiple `app_template` instances in parallel, but to run them sequentially.

Ah ok. I got excited prematurely.

**Comment by tchaikov** [comment]
v3:

- rebase against master HEAD
- disable `app_standard_memory_allocator` in C++ source file instead of using CMake.

**Pull request merged**
