### PR TITLE
file: add file_system_stat

### PR DESCRIPTION
**Pull request by bhalevy**
Return an abstract file_system_stat_data representing
the system statvfs for the filesystem identified
by the given file name.

The motivation is implementing a disk-space monitor
in scylladb.

### CODE REVIEW

**Comment by bhalevy** [comment]
- added `#include <coroutine>`

**Comment by bhalevy** [comment]
@xemul can you please review and consider merging?

**Comment by xemul** [comment]
This PR adds
- conversion from statvfs to newly introduced file_system_stat_data
- wrapper around already public reactor::statvfs()

So basically it adds 1:1 wrapper over existing APIs. What's the point?

**Comment by bhalevy** [comment]
> This PR adds
> 
> * conversion from statvfs to newly introduced file_system_stat_data
> * wrapper around already public reactor::statvfs()
> 
> So basically it adds 1:1 wrapper over existing APIs. What's the point?

The wrapper is similar to other "global" entry points we have so that callers won't need to access the reactor api.

As for the abstract file_system_stat_data, again, it's similar to the file stat_data struct that is not linux specific and provides an isolation layer.

**Comment by bhalevy** [comment]
ping @xemul

**Comment by bhalevy** [comment]
re-ping @xemul can we please merge this PR?

**Comment by bhalevy** [comment]
Replaced by https://github.com/scylladb/seastar/pull/2597

**Pull request closed without merging**
