### PR TITLE
build: pass -DBoost_NO_CXX98_FUNCTION_BASE to C++ compiler

### PR DESCRIPTION
**Pull request by BenPope**
Fix the case of `BOOST_VERSION_STRING` to `Boost_VERSION_STRING`

https://cmake.org/cmake/help/latest/module/FindBoost.html

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
thanks!

**Comment by tchaikov** [comment]
the build failures are not relevant, and should be addressed by #1782

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help merge this change?

**Comment by xemul** [comment]
f0b614214be37c745e0d6dfe940fd7db386a3783, but for some reason it didn't get closed

**Pull request closed without merging**
