### PR TITLE
tests: merge test_metrics.py into prometheus_test.py 

### PR DESCRIPTION
**Pull request by tchaikov**
in this series, we move all tests in `test_metrics.py` into `prometheus_test.py ` to drop the repeating code.

### CODE REVIEW

**Comment by tchaikov** [comment]
@amnonh this is a follow-up of #2237. could you take a look? i tested with prometheus 2.52.0 .

**Comment by tchaikov** [comment]
@amnonh hello Amnon, ping?

**Comment by amnonh** [comment]
@tchaikov I was on vacation, I'll take a look

**Comment by amnonh** [comment]
In general, it makes sense; that was my original comment when you added prometheus_test.py; why have two files for the same purpose when we can have one?

I haven't tested the code but I assume it works

**Review by amnonh — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
Amnon, thank you for your review and approval.

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help merge this change?

**Pull request merged**
