### PR TITLE
websocket: fix frame parsing and assembling.

### PR DESCRIPTION
**Pull request by balusch**
Signed-off-by: Jianyong Chen <baluschch@gmail.com>

### CODE REVIEW

**Comment by balusch** [comment]
A better fix should replace those magic numbers with constants, I'll make those cleanups in the next series, but now let's leave them as they are.

**Comment by xemul** [comment]
> Since we now deliver data to the user as long as it is available instead of waiting until all payload is parsed ...

I'm not completely up-to-date with websocket code :) but when you say "now" do you mean some specific commit that made this such?

**Comment by balusch** [comment]
> I'm not completely up-to-date with websocket code :) but when you say "now" do you mean some specific commit that made this such?

@xemul Hi Pavel, sorry for the ambiguity of my commit message, but no, **now** means the status quo(master branch, without my patch), I haven't introduce any change about that.

**Comment by balusch** [comment]
commit message updated.

**Comment by balusch** [comment]
@xemul could you please have another look?

**Pull request closed without merging**
