### PR TITLE
perftune.py: remove rx_queue_count from mode condition.

### PR DESCRIPTION
**Pull request by pveentjer**
On powerful instances like i3en.3xlarge and i3en.6xlarge the number
of logical cores is high, but the number of rx queues is equally high
and this causes these powerful instances to end up with the 'mq' mode.
With mq the network interrupts get spread over all cores instead of 
having isolated network IRQ cores which gives better performance.

This PR fixed that by removing the rx_queues_count from the mode
condition. This will cause the i3en.xlarge and the i3en.6xlarge
to end up with sq_split instead of mq.

The code is also simplified since the interface isn't relevant for the
mode calculation.

Fix https://github.com/scylladb/scylla-enterprise/issues/1250

See the above ticket for some performance benchmarks that have 
been executed. In short: it gives a significant improvement for the 
run throughput tests, but doesn't make a significant improvement 
for the run latency tests.

### CODE REVIEW

**Review by vladzcloudius — APPROVED** [review]
LGTM

**Comment by vladzcloudius** [comment]
@avikivity could you, please, consider this for merging?

**Comment by bhalevy** [comment]
ping, see https://github.com/scylladb/scylla-enterprise/issues/1250#issuecomment-1002483448

**Comment by dorlaor** [comment]
@bhalevy @slivne pls assign someone for this

**Comment by bhalevy** [comment]
> @bhalevy @slivne pls assign someone for this

@dor, according to @vladzcloudius this just needs to be merged (maybe rebased before since it's quite old, I'm not sure)

@avikivity is there anything preventing merging this fix?

**Comment by slivne** [comment]
@syuu1228 please review and approve this - huge machines need 2 CPU (4 VCPU) for networking interrupts. 

If avi left comments please take ownership of this.

**Review by syuu1228 — APPROVED** [review]
LGTM.

**Comment by slivne** [comment]
@avikivity merge ping

**Comment by slivne** [comment]
@avikivity merge ping

**Comment by vladzcloudius** [comment]
> I don't understand why sq is faster than mq in these cases.

Because of the lack of context switches due to HW interrupts on scylla CPUs.

**Comment by fee-mendes** [comment]
@avikivity - can we merge this? :-)
We just saw a situation on field where GCP n2-standard-16 vCPUs are being configured as `mq` - contributing to a performance impact

**Comment by DoronArazii** [comment]
@avikivity ping

**Comment by DoronArazii** [comment]
@avikivity @slivne 
Is issue affects the field, can we push this somehow?

**Comment by avikivity** [comment]
> > I don't understand why sq is faster than mq in these cases.
> 
> Because of the lack of context switches due to HW interrupts on scylla CPUs.

Yes, but we lose a core. 3xlarge has 6 cores, so one core is 17% of processing power. Some of it gets used for networking, but the rest is thrown away.

**Comment by avikivity** [comment]
The patch implies that for as little as 3 cores sq is better. That's throwing away a third of the processing power.

**Comment by vladzcloudius** [comment]
> The patch implies that for as little as 3 cores sq is better. That's throwing away a third of the processing power.

@avikivity This patch doesn't introduces this logic. It exists in perftune.py for years by now.
This patch simply moves the corresponding code from one place to another.

On top of that your statement is incorrect in general:
sq != sq_split.
Sq is only going to use a single HT for network handling, which is 1/8 of the total.
Only for 5 physical cores and up sq_split (which will take the whole core out would be used).
And when this logic was implemented the next possible config was 8 cores which would, again take note more than 1/8 of the total compute power.

**Comment by avikivity** [comment]
Right, I misread it.

I'm sad to lose the purely symmetric configuration, but I guess it doesn't work well. Maybe we can make the asymmetric configuration work better with IORING_SETUP_SQPOLL.

**Comment by vladzcloudius** [comment]
> Right, I misread it.
> 
> I'm sad to lose the purely symmetric configuration, but I guess it doesn't work well. 

Avi, please, don't get sad :)
The MQ mode is still there and can be used if needed. 

>Maybe we can make the asymmetric configuration work better with IORING_SETUP_SQPOLL.

We are constantly trying to improve already pretty awesome performance we deliver.
io_uring is the next "big thing" which is meant to outdate aio API and we will have to switch to it one day - you can't resist the Progress. 
And once we do we will definitely take a look at advanced features like IORING_SETUP_SQPOLL.

**Pull request closed without merging**
