### PR TITLE
Update IO stats label set

### PR DESCRIPTION
**Pull request by xemul**
This PR removes the obsoleted "ioshard" label and adds the "iogroup" one.

### CODE REVIEW

**Comment by xemul** [comment]
@avikivity , review ping

**Comment by xemul** [comment]
@scylladb/seastar-maint , review ping

**Comment by xemul** [comment]
@avikivity , that's not a bugfix, but without it we're going to have inconveniences looking at new consumption metrics on "older" scyllas that don't have this change. 

More details. The consumption value ranges between 0 and 100% * <number of io groups>. The "number of io groups" is defaulted to the number of numa nodes or can be configured by hand. Respectively, on scyllas w/o this change with more than one io group seeing e.g. 80% of consumption on the dashboard does _not_ mean that the disk is full. And to find this out we'll need to somehow check on each node the number of io groups configured. With this change dashboard will automagically split per-io-group metrics into 0-100% ranges.

Said that the question is -- does it worth backporting this non-fix?

**Comment by mykaul** [comment]
Since it improves supportability/debuggability, I'm in favor, especially if the risk is low.

**Pull request closed without merging**
