### PR TITLE
docs: use recent linux distro and GCC releases in documents

### LINKED ISSUE #1448: E: Unable to locate package liburing-dev
hi, I am trying to follow the installation instructions on https://github.com/scylladb/seastar

VERSION="20.04.5 LTS (Focal Fossa)"

After running $ sudo ./install-dependencies.sh I get an error

E: Unable to locate package liburing-dev

### PR DESCRIPTION
**Pull request by tchaikov**
as none of ubuntu 14.04/15.10/16.04 provide GCC-11 or up but Seastar requires at least GCC-11 or Clang 14 to buld. so bump up the ubuntu versions in the document as well. less confusion this way. the same applies to other popular distros.

also, for the same reason, let's reference GCC 11 and 12 in compatibility.md.

Fixes #1448
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
hello? ping for reviews.

**Comment by xemul** [comment]
I think that mentioning the exact version is quite onerously. In <some> <time-period> things will change again, and unless someone pays attention the docs would stay outdated. The only trustworthy source of what compilers we do support is circle-ci script that pins them explicitly by version.

**Comment by tchaikov** [comment]
@xemul hi Pavel, i merged all these `doc/building-*.md` into a single one. hopefully this should address both your concern and the alleviate #1448 .

could you take another look?

**Comment by xemul** [comment]
Yes, it now looks much better, but now I've noticed that the very same text exists in the root's README.md `Building Seastar` section. And it also has the reference on the HACKING.md with (surprise, surprise) pretty much the same text again.

So -- what's the point in having it in its 3rd form?

**Comment by tchaikov** [comment]
@xemul thank you for your reviews. indeed. i dropped them. and added the missing content to `README.md`. could you take another look?

**Pull request closed without merging**
