### PR TITLE
scripts: Remove build.sh

### PR DESCRIPTION
**Pull request by xemul**
It was supposed to be used in CI, but Circle-CI doesn't need it. Neither it's convenient enough e.g. it's impossible to add custom configuration options to it, so better drop

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help review this change?

**Comment by xemul** [comment]
@scylladb/seastar-maint , please review

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help review this change?

**Review by nyh — APPROVED** [review]
I don't know what this script was _supposed_ to be, but since @xemul wrote it, and now he says it's not useful, let's indeed drop it :-)

**Pull request closed without merging**
